trigger: none

pool:
  name: 'crc-cryptobot'

jobs:
- job: TestAgent
  displayName: "Test działania self-hosted agenta"
  steps:
  - script: |
      echo "Witaj, self-hosted agent działa!"
    displayName: "Wyświetlenie informacji o agencie"
